/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddRouteImport } from './routes/add'
import { Route as BoxRouteImport } from './routes/box'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as NewCategoryRouteImport } from './routes/new.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxRoute = BoxRouteImport.update({
  id: '/box',
  path: '/box',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewCategoryRoute = NewCategoryRouteImport.update({
  id: '/new/$category',
  path: '/new/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/box': typeof BoxRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/c/$category': typeof CCategoryRoute
  '/item/$id': typeof ItemIdRoute
  '/new/$category': typeof NewCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/box': typeof BoxRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/c/$category': typeof CCategoryRoute
  '/item/$id': typeof ItemIdRoute
  '/new/$category': typeof NewCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/box': typeof BoxRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/c/$category': typeof CCategoryRoute
  '/item/$id': typeof ItemIdRoute
  '/new/$category': typeof NewCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/box'
    | '/favorites'
    | '/search'
    | '/settings'
    | '/c/$category'
    | '/item/$id'
    | '/new/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/box'
    | '/favorites'
    | '/search'
    | '/settings'
    | '/c/$category'
    | '/item/$id'
    | '/new/$category'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/box'
    | '/favorites'
    | '/search'
    | '/settings'
    | '/c/$category'
    | '/item/$id'
    | '/new/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  BoxRoute: typeof BoxRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  CCategoryRoute: typeof CCategoryRoute
  ItemIdRoute: typeof ItemIdRoute
  NewCategoryRoute: typeof NewCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box': {
      id: '/box'
      path: '/box'
      fullPath: '/box'
      preLoaderRoute: typeof BoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/$category': {
      id: '/new/$category'
      path: '/new/$category'
      fullPath: '/new/$category'
      preLoaderRoute: typeof NewCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  BoxRoute: BoxRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  CCategoryRoute: CCategoryRoute,
  ItemIdRoute: ItemIdRoute,
  NewCategoryRoute: NewCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
